Repository CSC207-2022F-UofT/course-project-uplanit, pull requests merged in 2022-12, with the labels that each got.

#57 Organizing files. IMPORTANT FACTORING UPDATES. IMPORTANT OBJECT USE CHANGES.
  .idea/misc.xml
  src/main/java/Main.java
  src/main/java/ModifyEvent.java
  src/main/java/controllers/RecurrentEventController.java
  src/main/java/entities/Calendar.java
  src/main/java/entities/DynamicEvent.java
  src/main/java/entities/Event.java
  src/main/java/entities/EventFactory.java
  src/main/java/entities/RecurrentEvent.java
  src/main/java/entities/SingleEvent.java
  src/main/java/entities/Week.java
  src/main/java/presenters/RecurrentEventPresenter.java
  src/main/java/screens/RecurrentEventAddScreen.java
  src/main/java/tutorial/HelloWorld.java
  src/main/java/use_case_interactors/RecurrentEventInteractor.java
  src/test/java/entity_tests/EventEntityTest.java
  src/test/java/tutorial/HelloWorldTest.java
Labels: enhancement

#58 Calendar 2.0
  src/main/java/entities/Calendar.java
  src/main/java/entities/DynamicEvent.java
  src/main/java/entities/Event.java
  src/main/java/entities/EventFactory.java
  src/main/java/entities/RecurrentEvent.java
  src/main/java/entities/SingleEvent.java
  src/main/java/entities/Week.java
  src/test/java/entity_tests/EventEntityTest.java
Labels: Entity

#68 Feature 12 - Get dynamic goal statistics
  .idea/misc.xml
  .idea/vcs.xml
  src/main/java/screens/FileGoalStats.java
  src/main/java/screens/controllers/GoalStatsCalculatorController.java
  src/main/java/use_cases/dynamic_goal_statistics_use_case/DynamicGoalStatsDsGateway.java
  src/main/java/use_cases/dynamic_goal_statistics_use_case/DynamicGoalStatsDsRequestModel.java
  src/main/java/use_cases/dynamic_goal_statistics_use_case/DynamicGoalStatsInputBoundary.java
  src/main/java/use_cases/dynamic_goal_statistics_use_case/DynamicGoalStatsInteractor.java
  src/main/java/use_cases/dynamic_goal_statistics_use_case/DynamicGoalStatsPresenter.java
  src/main/java/use_cases/dynamic_goal_statistics_use_case/DynamicGoalStatsRequestModel.java
  src/main/java/use_cases/dynamic_goal_statistics_use_case/DynamicGoalStatsResponseModel.java
Labels: feature
